# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'School_Food_iOS_V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'FSCalendar'
  pod 'Moya/RxSwift'
  pod 'MaterialComponents/Cards'
  pod 'RealmSwift'
  pod 'RxCocoa'
  pod 'ReactorKit'

  # Pods for School_Food_iOS_V2

  target 'School_Food_iOS_V2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'School_Food_iOS_V2UITests' do
    # Pods for testing
  end

end
