# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'School_Food' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire', '~>5.0'
	pod 'FSCalendar'
	pod 'Moya/RxSwift', '~> 14.0'
  	pod 'RxCocoa'

  # Pods for School_Food

end
